schema:
  CacheResponseStatus: "Int64"
  ClientASN: "Int64"
  ClientCountry: "String"
  ClientIP: "String"
  ClientRequestHost: "String"
  ClientRequestMethod: "String"
  ClientRequestURI: "String"
  ClientRequestUserAgent: "String"
  EdgeColoID: "Int64"
  EdgeEndTimestamp: "Int64"
  EdgeRateLimitAction: "String"
  EdgeRateLimitID: "Int64"
  EdgeResponseBytes: "Int64"
  EdgeResponseStatus: "Int64"
  EdgeStartTimestamp: "Int64"
  OriginIP: "String"
  OriginResponseStatus: "Int64"
  OriginResponseTime: "Int64"
  RayID: "String"
  WAFAction: "String"
  WAFFlags: "String"
  WAFRuleID: "String"
  ZoneID: "Int64"
