schema:
  CacheResponseStatus: "Int16"
  ClientASN: "Int32"
  ClientCountry: "Categorical"
  ClientIP: "String"
  ClientRequestHost: "Categorical"
  ClientRequestMethod: "Categorical"
  ClientRequestURI: "String"
  ClientRequestUserAgent: "String"
  EdgeColoID: "Int16"
  EdgeEndTimestamp: "Int64"
  EdgeRateLimitAction: "Categorical"
  EdgeRateLimitID: "Int64"
  EdgeResponseBytes: "Int64"
  EdgeResponseStatus: "Int16"
  EdgeStartTimestamp: "Int64"
  OriginIP: "String"
  OriginResponseStatus: "Int16"
  OriginResponseTime: "Int64"
  RayID: "String"
  WAFAction: "Categorical"
  WAFFlags: "String"
  WAFRuleID: "String"
  ZoneID: "Int64"
